os:
- linux
language: nix
nix: 2.2.1
env:
  global:
    - secure: "mBjN9aye+Raelt87O42f6kVuYsOu3V7xcbtqnGwAC/NCjTO5gkcxtK/NSgc4jbw4t+onNuQa2LSBIr9QnDnoy1MYRBIZrLU4xTQK9PHCfubdm66YuNspuQ1TvnBei66jNkSmw67hkWwEL79zwUJYHn7LSX+XxrrRKa5YXofui/YAr7LxmemrmysPenF9X1WWyE44Dkj9zvci11XPVifUj7yhaYotcPR8cI1HnGgl4LGy1nikc8WQtxO+Y8PgtTt2IgKCjx5XcwrBp2D5PuDpfEvrN7AoXHBkc2Mv1VBmRcG4/3gcI+gly3Sg5vMixPqk2APJ/LyaTWcZZ/7fI/Z8fClOskUr2jOhtfxO2NChRh96QREZtesBqS4wzQmUanC4+GjrBsV/OgTBIXwYpvGMfDASLVLuY1LLPBUNWjk6ANPCxZoAGTLbfpOnpof1x98cS1SyQBNOtWyjmfh4QYQp3eQo/3H7VYKYnOdzmOgYf9qfC5O0GzFcvkmxfBfqvh/ZpkY7QmXzC+L7pGJM0JA3cmj5HFbQLTB2I2ZGv5M1mxKWHtZSOkorsZZ2SzYBjbdBbbvt//5R1yP+13fw5Y6V12WSRBYP2czF1jrDse+mHcWfbDUlr2ZdiiM9rHgyLhhItDYrcTqwzsH88vyylf6JLdHCwkPVEbQBOqgxDrr7fM8="
    - secure: "OABhdnyq+ZKtmTQxgTZLMjs0d5euYtXuwLAP/14+aL8cike2ppxzH3HAyNP9kB+1YukHeIbVRiR9BOZa9YvihENkPHsSfvs3uFq2zDK/Z0d+M3b+ltppbrb6MQYTTQrhK2ERqXLHwQnTIHTr3NlF9ggU4E1bbLTbnSz5FZk9X9Hz3PikoPqQ1+2UBTE0kEmKsJYw02FaH5Sx5G254NPjr8CzINeLBFFVZp1PMZrAM23K2awrjNccy4wkXhonkLV68852v6wFx0SpRdgLURfjJdjP1rZ0zllUWaMUIeexsniWFS5DXzt16G8Z1tdwJxiguNelfa1evDdTwMqLkOBEINszPZw/zHM5Jx/TdhVlFmw4GzumSyb9yf6vDjjuMti2uFc26boGin8ULQcyZhYxqy0anLIJyriWF16NMleZxggYIoyj5LzTsx88BtkTHCECULIjaH5cXXwoHZCVb+o8FkVHQOdoFy6jDvPnk48NX7fjwIeR2nZWh2gh0i4gA7ThuEOMoJw9S5eAOJI5n0Y6beL+GJIKJDZZzDXBsgEYrYwWp5i6gZVYXQFDCT7m9ww5A21qvEKRbNMzlTG646AfjJ29JKBEG38OSwhqpXyXDBQR2OwC3rO/lP/nJPtzznD7C4ZPdWEVZxIFQk/BaQ/3RnOp/JsFtdxPNKaJYQxSUrY="

branches:
  only:
    - develop

before_script:
  - echo "trusted-users = root $USER" | sudo tee -a /etc/nix/nix.conf
  - sudo launchctl kickstart -k system/org.nixos.nix-daemon || true

jobs:
  include:
    - stage: deploy
      script:
        - nix-env -iA cachix -f https://cachix.org/api/v1/install
        - cachix use alexpeits-travis
        - cachix push alexpeits-travis --watch-store &
        - nix-build -A site
        - mkdir -p site
        - rm -rf site/*
        - cp -R result/_build/* site/
        - chmod -R +w site/
        - sleep 10

      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        target_branch: master
        local_dir: site
        on:
          branch: develop
