title: Alex's blog
author: Alex Peitsinis
email: alexpeitsinis@gmail.com

baseurl: ""
url: "https://alexpeits.github.io"

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
plugins:
    - jekyll-feed

permalink: /articles/:short_year/:title.html

timezone: Europe/London
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']

post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md

git:
  branch: master

conf:
    show_comments: true

disqus:
    shortname: alexpeits-github-io

google_analytics: UA-116341417-1

twitter_username: alexpeits
github_username: alexpeits
github:
  username: alexpeits
  download: false
