---
site_title: Alex's blog
author: Alex Peitsinis
email: alexpeitsinis@gmail.com
copyright: © 2017–present Alex Peitsinis
host: https://alexpeits.github.io

syntax_highlight: pygments
math: mathjax
mermaid:
  ext: svg
  light_theme: default
  dark_theme: dark

nav:
  - name: Posts
    url: /
  - name: Tags
    url: /tags.html
  - name: About
    url: /pages/about.html
