version: 2
jobs:
  build:
    branches:
      only:
        - develop
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3
      - run:
          name: build blog
          command: |
            bundle exec jekyll build
      - deploy:
          name: deploy to master
          command: |
            if [ $CIRCLE_BRANCH == 'develop' ]; then
              bash .circleci/publish.sh
            fi
